/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package programa;

import java.util.Date;

/**
 *
 * @author josea
 */
public class Ventana extends javax.swing.JDialog {

    /**
     * Creates new form Ventana
     */
    Reserva reserva = new Reserva();
    EsNumero posibleNumero = new EsNumero();
    EsMail posibleMail = new EsMail();
    
    public Ventana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones1 = new javax.swing.ButtonGroup();
        grupoBotones2 = new javax.swing.ButtonGroup();
        grupoBotones3 = new javax.swing.ButtonGroup();
        tituloNumeroAsistentes = new javax.swing.JLabel();
        tituloNumeroJornadas = new javax.swing.JLabel();
        tituloHabitacione = new javax.swing.JLabel();
        numeroAsistentes = new javax.swing.JSpinner();
        numeroJornadas = new javax.swing.JSpinner();
        panelPersonales = new javax.swing.JPanel();
        selectorFecha = new javax.swing.JSpinner();
        areaNombre = new javax.swing.JTextField();
        tituloNombre1 = new javax.swing.JLabel();
        areaTelefono = new javax.swing.JTextField();
        tituloNombre2 = new javax.swing.JLabel();
        tituloNombre = new javax.swing.JLabel();
        tituloNombre3 = new javax.swing.JLabel();
        areaEmail = new javax.swing.JTextField();
        tituloVentanaReserva = new javax.swing.JLabel();
        panelEvento = new javax.swing.JPanel();
        selectorBanquete = new javax.swing.JRadioButton();
        selectorJornada = new javax.swing.JRadioButton();
        selectorCongreso = new javax.swing.JRadioButton();
        panelComida = new javax.swing.JPanel();
        selectorBufe = new javax.swing.JRadioButton();
        selectorCarta = new javax.swing.JRadioButton();
        selectorSinCita = new javax.swing.JRadioButton();
        selectorConCita = new javax.swing.JRadioButton();
        separador = new javax.swing.JSeparator();
        numeroHabitaciones = new javax.swing.JSpinner();
        botonGrabar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Reservas");
        setResizable(false);

        tituloNumeroAsistentes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNumeroAsistentes.setText("Número de Asistentes:");

        tituloNumeroJornadas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNumeroJornadas.setText("Número de Jornadas del Congreso:");

        tituloHabitacione.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloHabitacione.setText("Número de Habitaciones:");

        numeroAsistentes.setModel(new javax.swing.SpinnerNumberModel());

        numeroJornadas.setModel(new javax.swing.SpinnerNumberModel());
        numeroJornadas.setEnabled(false);

        panelPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        selectorFecha.setModel(new javax.swing.SpinnerDateModel());

        areaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaNombreActionPerformed(evt);
            }
        });

        tituloNombre1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNombre1.setText("Telefono:");

        tituloNombre2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNombre2.setText("Fecha del Evento:");

        tituloNombre.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNombre.setText("Nombre:");

        tituloNombre3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tituloNombre3.setText("Email:");

        areaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonalesLayout = new javax.swing.GroupLayout(panelPersonales);
        panelPersonales.setLayout(panelPersonalesLayout);
        panelPersonalesLayout.setHorizontalGroup(
            panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addComponent(tituloNombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addComponent(tituloNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloNombre1)
                            .addComponent(tituloNombre))
                        .addGap(34, 34, 34)
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(areaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelPersonalesLayout.setVerticalGroup(
            panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloNombre))
                .addGap(18, 18, 18)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNombre1)
                    .addComponent(areaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNombre3)
                    .addComponent(areaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNombre2)
                    .addComponent(selectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tituloVentanaReserva.setBackground(new java.awt.Color(204, 204, 204));
        tituloVentanaReserva.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        tituloVentanaReserva.setForeground(new java.awt.Color(0, 153, 153));
        tituloVentanaReserva.setText("Formulario Reservas Salón Habana.");

        panelEvento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        grupoBotones3.add(selectorBanquete);
        selectorBanquete.setText("Banquete");
        selectorBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorBanqueteActionPerformed(evt);
            }
        });

        grupoBotones3.add(selectorJornada);
        selectorJornada.setText("Jornada");
        selectorJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorJornadaActionPerformed(evt);
            }
        });

        grupoBotones3.add(selectorCongreso);
        selectorCongreso.setText("Congreso");
        selectorCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorCongresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEventoLayout = new javax.swing.GroupLayout(panelEvento);
        panelEvento.setLayout(panelEventoLayout);
        panelEventoLayout.setHorizontalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectorBanquete)
                    .addComponent(selectorJornada)
                    .addComponent(selectorCongreso))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelEventoLayout.setVerticalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(selectorBanquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorJornada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorCongreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Comida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        grupoBotones1.add(selectorBufe);
        selectorBufe.setText("Bufé");

        grupoBotones1.add(selectorCarta);
        selectorCarta.setText("Carta");

        grupoBotones2.add(selectorSinCita);
        selectorSinCita.setText("No pedir cinta con el Chef");

        grupoBotones2.add(selectorConCita);
        selectorConCita.setText("Pedir cita con el Chef");
        selectorConCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorConCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComidaLayout = new javax.swing.GroupLayout(panelComida);
        panelComida.setLayout(panelComidaLayout);
        panelComidaLayout.setHorizontalGroup(
            panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectorBufe)
                    .addComponent(selectorCarta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectorSinCita)
                    .addComponent(selectorConCita))
                .addGap(20, 20, 20))
        );
        panelComidaLayout.setVerticalGroup(
            panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComidaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorBufe)
                    .addComponent(selectorSinCita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorCarta)
                    .addComponent(selectorConCita))
                .addGap(27, 27, 27))
        );

        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numeroHabitaciones.setModel(new javax.swing.SpinnerNumberModel());
        numeroHabitaciones.setEnabled(false);

        botonGrabar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        botonGrabar.setText("Grabar Reserva.");
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(panelComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloNumeroAsistentes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloNumeroJornadas)
                                    .addComponent(tituloHabitacione))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tituloVentanaReserva)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloVentanaReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloNumeroAsistentes)
                    .addComponent(numeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNumeroJornadas)
                    .addComponent(numeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloHabitacione)
                    .addComponent(numeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGrabar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectorConCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorConCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorConCitaActionPerformed

    private void selectorCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorCongresoActionPerformed
        numeroJornadas.setEnabled(true);
        numeroHabitaciones.setEnabled(true);
    }//GEN-LAST:event_selectorCongresoActionPerformed

    private void selectorBanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorBanqueteActionPerformed
        numeroJornadas.setEnabled(false);
        numeroHabitaciones.setEnabled(false);
    }//GEN-LAST:event_selectorBanqueteActionPerformed

    private void selectorJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorJornadaActionPerformed
        numeroJornadas.setEnabled(false);
        numeroHabitaciones.setEnabled(false);
    }//GEN-LAST:event_selectorJornadaActionPerformed

    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        reserva.setNombre(areaNombre.getText());
        
        if(true==posibleMail.esMail(String.valueOf(areaEmail.getText()))){
            reserva.setEmail(areaEmail.getText());
        }
        
        if (true==posibleNumero.esNumero(String.valueOf(areaTelefono.getText()))){
            reserva.setTelefono(areaTelefono.getText());
        }
        
        reserva.setAsistentes((int) numeroAsistentes.getValue());
        reserva.setFecha((Date) selectorFecha.getValue());
        reserva.setHabitaciones((int) numeroHabitaciones.getValue());
        reserva.setJornadas((int) numeroJornadas.getValue());
        //sigue en seleccionar el dato de los grupos de botones.
        if (selectorBanquete.isSelected()== true){
            reserva.setT_evento("Banquete");
        }
        if (selectorCongreso.isShowing()==true){
            reserva.setT_evento("Congreso");
        }
        if (selectorJornada.isSelected()==true){
            reserva.setT_evento("Jornada");
        }
        if (selectorBufe.isSelected()==true){
            reserva.setT_comida("bufe");
        }
        if (selectorCarta.isSelected()==true){
            reserva.setT_comida("Carta");
        }
        if (selectorConCita.isSelected()==true){
            reserva.setCheff(true);
        }else{reserva.setCheff(false);}
       
        System.out.println(reserva.toString());
        
        this.setVisible(false);//cierra la ventana de reservas
    }//GEN-LAST:event_botonGrabarActionPerformed

    private void areaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaNombreActionPerformed

    private void areaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana dialog = new Ventana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaEmail;
    private javax.swing.JTextField areaNombre;
    private javax.swing.JTextField areaTelefono;
    private javax.swing.JButton botonGrabar;
    private javax.swing.ButtonGroup grupoBotones1;
    private javax.swing.ButtonGroup grupoBotones2;
    private javax.swing.ButtonGroup grupoBotones3;
    private javax.swing.JSpinner numeroAsistentes;
    private javax.swing.JSpinner numeroHabitaciones;
    private javax.swing.JSpinner numeroJornadas;
    private javax.swing.JPanel panelComida;
    private javax.swing.JPanel panelEvento;
    private javax.swing.JPanel panelPersonales;
    private javax.swing.JRadioButton selectorBanquete;
    private javax.swing.JRadioButton selectorBufe;
    private javax.swing.JRadioButton selectorCarta;
    private javax.swing.JRadioButton selectorConCita;
    private javax.swing.JRadioButton selectorCongreso;
    private javax.swing.JSpinner selectorFecha;
    private javax.swing.JRadioButton selectorJornada;
    private javax.swing.JRadioButton selectorSinCita;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel tituloHabitacione;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloNombre1;
    private javax.swing.JLabel tituloNombre2;
    private javax.swing.JLabel tituloNombre3;
    private javax.swing.JLabel tituloNumeroAsistentes;
    private javax.swing.JLabel tituloNumeroJornadas;
    private javax.swing.JLabel tituloVentanaReserva;
    // End of variables declaration//GEN-END:variables
}
